Update dev-CI-CD-pipeline.yml
Co-Authored-By: Giles Synaeve <145968081+GilesS420@users.noreply.github.com>
Co-Authored-By: senneclauwaert <183754009+senneclauwaert@users.noreply.github.com>

diff --git a/.github/workflows/dev-CI-CD-pipeline.yml b/.github/workflows/dev-CI-CD-pipeline.yml
--- a/.github/workflows/dev-CI-CD-pipeline.yml
+++ b/.github/workflows/dev-CI-CD-pipeline.yml
@@ -97,8 +97,7 @@ jobs:
       - name: Deploy to Development Server
         if: ${{ !inputs.test_mode }}
         run: |
-          ssh -o StrictHostKeyChecking=no -tt -p 20022 student@${{ secrets.DNS_NAME }} << 'EOF'
-
+          ssh -o StrictHostKeyChecking=no -o ServerAliveInterval=60 -o ServerAliveCountMax=10 -tt -p 20022 student@${{ secrets.DNS_NAME }} << 'EOF'
             set -e
             echo 'Student1' | sudo -S mkdir -p /root/billing/attendify-billing
 
@@ -112,23 +111,23 @@ jobs:
               set -e
               cd /root/billing/attendify-billing
 
-            if [ ! -d ".git" ]; then
-              echo "No git repo found here. Exiting."
-              exit 1
-            fi
+              if [ ! -d ".git" ]; then
+                echo "No git repo found here. Exiting."
+                exit 1
+              fi
 
-            git fetch --all
-            git reset --hard origin/main
+              git fetch --all
+              git reset --hard origin/main
 
-            if [ ! -f "docker-compose.yml" ]; then
-              echo "Error: docker-compose.yml not found in repo"
-              exit 1
-            fi
+              if [ ! -f "docker-compose.yml" ]; then
+                echo "Error: docker-compose.yml not found in repo"
+                exit 1
+              fi
 
-            docker compose -f docker-compose.yml up -d --build || { echo "Docker Compose up failed!"; docker compose logs --tail=100; exit 1; }
-            sleep 10
+              docker compose -f docker-compose.yml up -d --build || { echo "Docker Compose up failed!"; docker compose logs --tail=100; exit 1; }
+              sleep 10
 
-            docker ps | grep billing-consumer || docker ps | grep billing-producer || { echo "Billing containers not running!"; docker compose logs --tail=100; exit 1; }
+              docker ps | grep billing-consumer || docker ps | grep billing-producer || { echo "Billing containers not running!"; docker compose logs --tail=100; exit 1; }
             '
           EOF
 
